# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
  connection-timeout: 5000ms
  servlet:
    context-path: /uniedp-web
    session:
      cookie:
        http-only: true

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  activiti:
    check-process-definitions: false
  # 初始化表
  flyway:
    # 是否开启版本升级
    enabled: true
    # 自动创建表
    baseline-on-migrate: true
    # 版本号存储表名
    table: sys_schema_history
    # 版本号无序执行
    out-of-order: true
    baseline-version: 0
  datasource:
    druid:
      filter:
        wall:
          config:
          # 解决druid与flyway冲突
      filters: stat,logback

fdfs:
  so-timeout: 600000
  connect-timeout: 6000
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.10.10:22122

# 是否开启redis缓存  true开启   false关闭
#uniedp.redis.open: false
# 是否开启dict字典启动加载  true开启   false关闭
uniedp:
  dict:
    load: true
  log:
    open: true
