spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/newsail_test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: ****
      password: ****
#      #Oracle
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@localhost:1521:xe
#      username: xxxx
#      password: 123456
#      #SQLServer
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=security_enterprise
#      username: sa
#      password: 123456
#      #postgresql
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/security_enterprise
#      username: postgres
#      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  cache:
    type: GENERIC
##j2cache stater
j2cache:
  config-location: /j2cache-test.properties
  allow-null-values: false
  cache-clean-mode: passive
  redis-client: lettuce
  open-spring-cache: true


### xxl-job admin address list, such as "http://address"
### or "http://address01,http://address02"
xxl:
  job:
    open: false
    admin:
      addresses: http://127.0.0.1:9080/xxl-job-admin
    ### xxl-job executor address
    executor:
      appname: uniedp-job-executor
      ip:
      port: 9009
      ### xxl-job log path
      logpath: applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1
    ### xxl-job, access token
    accessToken:

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml,classpath:META-INF/modeler-mybatis-mappings/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.uniedp.modules.*.entity
  configuration-properties:
    blobType: BLOB
    boolValue: TRUE
    prefix:
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      #db-type: mysql
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
##多数据源的配置，需要引用frk-dynamic-datasource
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://123456:1433;DatabaseName=security_enterprise
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://123456:5432/security_enterprise
#      username: postgres
#      password: 123456